version: '3.8'

# Docker-Compose 方式启动容器的 YAML 配置文件
# 当前配置仅保证可以启动容器；更多配置参数请参考镜像 README.md 文档中说明
services:
  grafana:
    image: registry.cn-shenzhen.aliyuncs.com/colovu/grafana:latest
    restart: always
    ports:
      - '3000:3000'
    environment:
      - 'GF_SECURITY_ADMIN_PASSWORD=colovu'

